proxy:
  hosts:
    - www.datocms.com
    - www-draft.datocms.com

env:
  clear:
    DRAFT_MODE_HOSTNAME: www-draft.datocms.com
    DEPLOYMENT_DESTINATION: production

builder:
  args:
    PUBLIC_HOSTNAME: www.datocms.com
